version: '3.9'

services: 
    server:
        command: 'npm start'
        build: .
        ports: 
            - '3000:3000'
    db:
        image: 'postgres'
        ports: 
            - '5432:5432'
        environment: 
            POSTGRES_PASSWORD: 'password'
            POSTGRES_USER: 'docker'