name: Test
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch  
  pull_requests:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: install dependancies
        run: npm install

      - name: run test
        run: npm run test